language: java

notifications:
  email: false

sudo: false

jdk:
  - oraclejdk8 

before_script:
  - mvn pmd:check
  - mvn pmd:cpd-check
  - cat target/pmd.xml


after_script:
  - mvn checkstyle:check --batch-mode --fail-never